#	server:
#   port: 因为会启动多个 product-data-service, 所以端口号由用户自动设置，推荐 8001,8002,8003

spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    #微服务名字
    name: session-service
  datasource:
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/FoodCooperation?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        #        连接池最大连接数
        max-active: 100
        #        最大等待时间
        max-wait: 5s
        #        最大空闲数
        max-idle: 8
        #        最小空闲数
        min-idle: 0
        #    连接超时时间
        timeout: 3s
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 173220160@qq.com #发送邮件的邮箱地址
    password:  pduiqzilcrdmbgeh #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 173220160@qq.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.scau.springcloud.mapper
eureka:
  client:
    serviceUrl:
      #注册中心地址
      defaultZone: http://localhost:8761/eureka/


