#	server:
#   port: 因为会启动多个 product-data-service, 所以端口号由用户自动设置，推荐 8001,8002,8003

spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    #微服务名字
    name: cooperation-service
  datasource:
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/FoodCooperation?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        #        连接池最大连接数
        max-active: 100
        #        最大等待时间
        max-wait: 5s
        #        最大空闲数
        max-idle: 8
        #        最小空闲数
        min-idle: 0
        #    连接超时时间
        timeout: 3s
#  dubbo消费
#  dubbo:
#    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
#      name: consumer
#    registry:                 #注册中心配置，用于配置连接注册中心相关信息。
#      address: zookeeper://127.0.0.1:2181
#    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受（订阅）。
#      name: dubbo
#      port: 20880
#    consumer:
#      check: false
#    reference:
#      loadbalance: roundrobin
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.scau.springcloud.mapper
eureka:
  client:
    serviceUrl:
      #注册中心地址
      defaultZone: http://localhost:8761/eureka/
#允许访问 /actuator/bus-refresh
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
#断路器
feign:
  hystrix:
    enabled: true


