#	server:
#   port: 因为会启动多个 product-data-service, 所以端口号由用户自动设置，推荐 8001,8002,8003

spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    #微服务名字
    name: session-service
eureka:
  client:
    serviceUrl:
      #注册中心地址
      defaultZone: http://localhost:8761/eureka/

redis:
  node:
    maxTotal: 10
    host: localhost
    port: 6379
